[workspace]
members = [
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "day8"]
resolver = "2"

[workspace.dependencies]
regex = "1.10.2"
itertools = "0.12.0"
num = "0.4.1"
